import '../styles/globals.css';
import Navbar from './components/Navbar';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html>
			<head />
			<body>
				<main className="bg-gray-100 min-h-screen w-screen">
					<main className="max-w-screen-2xl m-auto bg-white">
						<Navbar />
						{children}
					</main>
				</main>
			</body>
		</html>
	)
}
